### ISSUE TITLE
Add GA tracking code and heatmap

### ISSUE THREAD

**Issue by VivianChu** [ucsdlib/ceo#1]
Hi Vivian,

If it's not already there, can you add Google Analytics tracking code to the CEO website

The snippet should be added just before the closing body tag. 

<script>

(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function()
{(i[r].q=i[r].q||[]).push(arguments)}

,i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-3409104-8', 'auto');

ga('set', 'anonymizeIp', true);

ga('send', 'pageview');

</script>

 

Last add heatmap tracking. Here is the code:

<script type="text/javascript" src="//script.crazyegg.com/pages/scripts/0026/4339.js" async="async"></script>

Here are the installation instructions:
https://help.crazyegg.com/article/43-crazy-egg-manual-installation.

**Comment by VivianChu** [comment]
@gamontoya - GA tracking code and heatmap has been added to ceo and deployed to staging.
For example
view-source:http://librarytest.ucsd.edu/ceo/frames_mainnav.html
Do you want me to create a release to get it deployed to prod?  Thanks

**Comment by gamontoya** [comment]
@VivianChu Looks like I didn't put in the comment after all. Yes, please proceed. Thank you.

**Comment by VivianChu** [comment]
@gamontoya - GA tracking and heatmap have been added to 236 static html pages and deployed to staging.  I don't have crazyegg account.  Could you take a look? Thanks
http://librarytest.ucsd.edu/ceo/publications/index.html

**Comment by gamontoya** [comment]
@VivianChu I don't have crazy egg either.

**Comment by gamontoya** [comment]
@VivianChu Why not just push to prod and Jenn and SuHui can let us know if it's working?

**Comment by VivianChu** [comment]
@gamontoya - CEO and solr/velocity templates have been deployed to prod.  I checked and my chages are there.  https://library.ucsd.edu/ceo/index.html
Could you let Jen and SuHui know if it's working?  Thanks

**Comment by gamontoya** [comment]
@VivianChu Great. I'll let them know. Thank you!
