### ISSUE TITLE
Release 1.0.1

### ISSUE THREAD

**Issue by VivianChu** [ucsdlib/ceo#3]
### Descriptive summary

- CEO Version 1.0.1
- Release Manager: @VivianChu
- Product Owner: @gamontoya
- Operations: @rstanonik 

### To Verify

- [x] #1

**Comment by VivianChu** [comment]
@rstanonik - Could you deploy new CEO release to production at your earliest convenient?  Thanks

**Comment by rstanonik** [comment]
I deployed it to production just now

**Comment by VivianChu** [comment]
@rstanonik - I didn't see my change there.  Could you take a look?  Thanks
view-source:https://library.ucsd.edu/ceo/frames_mainnav.html
It should have the GA tracking code.

**Comment by rstanonik** [comment]
I don't know what GA tracking code looks like.
What should I look for?
Do you put a version in any of the files?
All of the files are dated  Apr 25 09:22

**Comment by rstanonik** [comment]
The jenkins log about the deploy contains.

 > git checkout -f 5f1a1d4f04c1e3e7fbf12f5a30936f1329330015
Commit message: "Add GA tracking code and heatmap"

**Comment by rstanonik** [comment]
https://lib-jenkins.ucsd.edu/job/Dams4%20Prod/job/ceo/7/console

**Comment by VivianChu** [comment]
@rstanonik - If you do view source in test env, you will see the ga tracking code.  view-source:http://librarytest.ucsd.edu/ceo/frames_mainnav.html
It will have this part
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-3409104-8', {cookieDomain: window.location.hostname});
  ga('set', 'anonymizeIp', true);
  ga('send', 'pageview');
</script>
<script type="text/javascript" src="//script.crazyegg.com/pages/scripts/0026/4339.js" async="async"></script>
Can you ssh into library and look at the file frames_mainnav.html  to make sure it has the above script?  Thanks

**Comment by rstanonik** [comment]
The code is there in production (on library)

grep "'ga'" frames_mainnav.html
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

**Comment by rstanonik** [comment]
Wait, it's not there, is it?

**Comment by rstanonik** [comment]
Yes, it is there.  Here's from the file on library
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i
[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.
getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(wi
ndow,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-3409104-8', {cookieDomain: window.location.hostname});
  ga('set', 'anonymizeIp', true);
  ga('send', 'pageview');

**Comment by rstanonik** [comment]
I see, ceo is located in a different place in prod, than in staging.

**Comment by VivianChu** [comment]
@rstanonik -  From browser, I still didn't see that code.

**Comment by rstanonik** [comment]
Okay, look now

**Comment by VivianChu** [comment]
@rstanonik - It's there now.  Thanks.
