### ISSUE TITLE
Release 1.0.2

### ISSUE THREAD

**Issue by VivianChu** [ucsdlib/ceo#5]
### Descriptive summary

- CEO Version 1.0.2
- Release Manager: @VivianChu
- Product Owner: @gamontoya
- Operations: @rstanonik 

### To Verify

- [x] #1

**Comment by VivianChu** [comment]
@rstanonik - Could you deploy new CEO release and ceo velocity templates in https://github.com/ucsdlib/dams4-solr to production?  Thanks

**Comment by rstanonik** [comment]
I deployed the solr_config (which includes velocity templates) and ceo to production.
The solr_config deploy restarted solr

**Comment by VivianChu** [comment]
Thanks so much @rstanonik .  My changes are there.
